from fastapi import APIRouter, Body

from app.core.models.ai import GeneratedStyleSpecResponse, PromptGenerateRequest
from app.core.models.style_spec import StyleSpec

router = APIRouter(prefix="/ai", tags=["ai"])


def _build_mock_captureone_keys(prompt: str) -> dict[str, str | int | float]:
    normalized = prompt.lower()
    keys: dict[str, str | int | float] = {
        "Exposure": 0.2,
        "Contrast": 8,
        "Saturation": 6,
        "Clarity": 8,
        "ToneCurve": "Film Standard",
    }

    if "moody" in normalized or "dark" in normalized:
        keys["Exposure"] = -0.2
        keys["Contrast"] = 12
        keys["Saturation"] = 4
    elif "bright" in normalized or "airy" in normalized:
        keys["Exposure"] = 0.45
        keys["Contrast"] = 6
        keys["Saturation"] = 7

    if "warm" in normalized:
        keys["ColorBalanceRed"] = 4
    elif "cool" in normalized:
        keys["ColorBalanceBlue"] = 4

    return keys


@router.post(
    "/generate-style-spec",
    response_model=GeneratedStyleSpecResponse,
    summary="Generate StyleSpec From Prompt",
    description=(
        "Generate a Capture One-compatible `StyleSpec` from a natural-language prompt. "
        "Phase 1 implementation uses a deterministic mock provider."
    ),
    response_description="Generated style specification and generation metadata.",
)
def generate_style_spec(
    payload: PromptGenerateRequest = Body(..., description="Prompt-based generation payload."),
) -> GeneratedStyleSpecResponse:
    prompt = payload.prompt.strip()
    intents = payload.intent if payload.intent else ["cinematic", "balanced"]
    keys = _build_mock_captureone_keys(prompt)

    generated = StyleSpec(
        name=f"AI {prompt[:40]}".strip(),
        intent=intents,
        captureone={
            "keys": keys,
            "notes": "Generated by mock provider. Replace with real LLM provider in next phase.",
        },
    )

    return GeneratedStyleSpecResponse(
        style_spec=generated,
        rationale="Mock rule-based generation applied from prompt keywords.",
        warnings=[],
        provider="mock",
        model="mock-v1",
    )
