from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Literal, Protocol

from app.core.models import AIGenerationRecord, AIChatSession, AIChatTurn, Artifact, RunnerJob, Style, StyleVersion


class Store(Protocol):
    base_dir: Path

    def create_style(self, style: Style) -> Style: ...
    def get_style(self, style_id: str) -> Style | None: ...
    def list_styles(self) -> list[Style]: ...

    def create_version(self, style_id: str, version: StyleVersion) -> StyleVersion: ...
    def get_version(self, style_id: str, version: str) -> StyleVersion | None: ...

    def save_artifact(
        self,
        style_id: str,
        version: str,
        target: Literal["captureone"],
        filename: str,
        content: bytes,
    ) -> Artifact: ...
    def get_artifact(self, artifact_id: str) -> tuple[Artifact, bytes] | None: ...
    def list_artifacts(self, style_id: str | None = None) -> list[Artifact]: ...

    def create_runner_job(self, job: RunnerJob) -> RunnerJob: ...
    def get_runner_job(self, job_id: str) -> RunnerJob | None: ...
    def list_runner_jobs(
        self,
        *,
        status: str | None = None,
        limit: int | None = None,
    ) -> list[RunnerJob]: ...
    def update_runner_job(
        self,
        job_id: str,
        *,
        status: str | None = None,
        claimed_by: str | None = None,
        locked_until: datetime | None = None,
        attempt_inc: int = 0,
        result: dict | None = None,
        error: str | None = None,
        logs: list[dict] | None = None,
    ) -> RunnerJob | None: ...
    def claim_runner_job(self, job_id: str, *, claimed_by: str = "runner") -> RunnerJob | None: ...

    def create_ai_generation(self, record: AIGenerationRecord) -> AIGenerationRecord: ...
    def list_ai_generations(self, *, limit: int | None = None) -> list[AIGenerationRecord]: ...

    def create_ai_chat_session(self, session: AIChatSession) -> AIChatSession: ...
    def get_ai_chat_session(self, session_id: str) -> AIChatSession | None: ...
    def update_ai_chat_session(self, session: AIChatSession) -> AIChatSession | None: ...

    def create_ai_chat_turn(self, turn: AIChatTurn) -> AIChatTurn: ...
    def get_ai_chat_turn(self, session_id: str, turn_id: str) -> AIChatTurn | None: ...
    def list_ai_chat_turns(self, session_id: str, *, limit: int | None = None) -> list[AIChatTurn]: ...
    def update_ai_chat_turn(self, turn: AIChatTurn) -> AIChatTurn | None: ...
