from __future__ import annotations

from app.core.models.ai import GeneratedStyleSpecResponse, PromptGenerateRequest
from app.core.models.style_spec import StyleSpec


class MockStyleGenerator:
    def __init__(self, *, model: str = "mock-v1") -> None:
        self.provider = "mock"
        self.model = model

    def generate_style_spec(self, payload: PromptGenerateRequest) -> GeneratedStyleSpecResponse:
        prompt = payload.prompt.strip()
        intents = payload.intent if payload.intent else ["cinematic", "balanced"]
        keys = _build_mock_captureone_keys(prompt)

        generated = StyleSpec(
            name=f"AI {prompt[:40]}".strip(),
            intent=intents,
            captureone={
                "keys": keys,
                "notes": "Generated by mock provider. Replace with real LLM provider in next phase.",
            },
        )

        return GeneratedStyleSpecResponse(
            style_spec=generated,
            rationale="Mock rule-based generation applied from prompt keywords.",
            warnings=[],
            provider=self.provider,
            model=self.model,
        )


def _build_mock_captureone_keys(prompt: str) -> dict[str, str | int | float]:
    normalized = prompt.lower()
    keys: dict[str, str | int | float] = {
        "Exposure": 0.2,
        "Contrast": 8,
        "Saturation": 6,
        "Clarity": 8,
        "Highlights": -6,
        "Shadows": 8,
        "WhiteBalanceTemperature": 5600,
        "WhiteBalanceTint": 2,
        "ColorBalanceRed": 3,
        "ColorBalanceGreen": 0,
        "ColorBalanceBlue": -2,
        "ToneCurve": "Film Standard",
    }

    if "moody" in normalized or "dark" in normalized:
        keys["Exposure"] = -0.2
        keys["Contrast"] = 12
        keys["Saturation"] = 4
    elif "bright" in normalized or "airy" in normalized:
        keys["Exposure"] = 0.45
        keys["Contrast"] = 6
        keys["Saturation"] = 7

    if "warm" in normalized:
        keys["WhiteBalanceTemperature"] = 6100
        keys["WhiteBalanceTint"] = 4
        keys["ColorBalanceRed"] = 4
    elif "cool" in normalized:
        keys["WhiteBalanceTemperature"] = 5000
        keys["WhiteBalanceTint"] = -2
        keys["ColorBalanceBlue"] = 4

    if "teal" in normalized:
        keys["ColorBalanceBlue"] = 6
        keys["Saturation"] = 8
    if "portrait" in normalized:
        keys["Highlights"] = -10
        keys["Shadows"] = 12

    return keys
