from __future__ import annotations

from app.core.ai.look_profiles import apply_creative_direction, expand_style_references, infer_intensity
from app.core.models.ai import (
    AIHealthResponse,
    AIPlannerTrace,
    AIPromptPreviewResponse,
    GeneratedStyleSpecResponse,
    PromptGenerateRequest,
)
from app.core.models.style_spec import StyleSpec


class MockStyleGenerator:
    def __init__(self, *, model: str = "mock-v1") -> None:
        self.provider = "mock"
        self.model = model

    def generate_style_spec(self, payload: PromptGenerateRequest) -> GeneratedStyleSpecResponse:
        expansion = expand_style_references(payload.prompt.strip(), payload.intent)
        prompt = expansion.expanded_prompt
        intents = list(payload.intent) if payload.intent else ["cinematic", "balanced"]
        for intent in expansion.added_intents:
            if intent not in intents:
                intents.append(intent)
        keys = _build_mock_captureone_keys(prompt, payload.constraints)

        generated = StyleSpec(
            name=f"AI {prompt[:40]}".strip(),
            intent=intents,
            captureone={
                "keys": keys,
                "notes": "Generated by mock provider. Replace with real LLM provider in next phase.",
            },
        )
        constraints = payload.constraints if isinstance(payload.constraints, dict) else {}
        family_id = constraints.get("family_id")

        return GeneratedStyleSpecResponse(
            style_spec=generated,
            rationale="Mock rule-based generation applied from prompt keywords.",
            warnings=[],
            provider=self.provider,
            model=self.model,
            planner_trace=AIPlannerTrace(
                mode="mock_rule_based",
                family_id=family_id if isinstance(family_id, str) and family_id.strip() else None,
                intensity=infer_intensity(prompt, payload.constraints),
                source="mock rule-based generator",
            ),
        )

    def preview_prompt(self, payload: PromptGenerateRequest) -> AIPromptPreviewResponse:
        rendered = (
            "Mock provider does not call an external model. "
            f"Prompt received: {payload.prompt!r}. Intents: {payload.intent or []}."
        )
        return AIPromptPreviewResponse(
            provider=self.provider,
            model=self.model,
            prompt=rendered,
            examples_count=0,
            examples=[],
        )

    def health_check(self) -> AIHealthResponse:
        return AIHealthResponse(
            status="available",
            available=True,
            provider=self.provider,
            model=self.model,
            message="Mock provider is available locally.",
        )


def _build_mock_captureone_keys(
    prompt: str, constraints: dict | None = None
) -> dict[str, str | int | float]:
    normalized = prompt.lower()
    keys: dict[str, str | int | float] = {
        "Exposure": 0.2,
        "Contrast": 8,
        "Saturation": 6,
        "Clarity": 8,
        "Highlights": -6,
        "Shadows": 8,
        "WhiteBalanceTemperature": 5600,
        "WhiteBalanceTint": 2,
        "ColorBalanceRed": 3,
        "ColorBalanceGreen": 0,
        "ColorBalanceBlue": -2,
        "ToneCurve": "Film Standard",
    }

    if "moody" in normalized or "dark" in normalized:
        keys["Exposure"] = -0.2
        keys["Contrast"] = 12
        keys["Saturation"] = 4
    elif "bright" in normalized or "airy" in normalized:
        keys["Exposure"] = 0.45
        keys["Contrast"] = 6
        keys["Saturation"] = 7

    if "warm" in normalized:
        keys["WhiteBalanceTemperature"] = 6100
        keys["WhiteBalanceTint"] = 4
        keys["ColorBalanceRed"] = 4
    elif "cool" in normalized:
        keys["WhiteBalanceTemperature"] = 5000
        keys["WhiteBalanceTint"] = -2
        keys["ColorBalanceBlue"] = 4

    if "teal" in normalized:
        keys["ColorBalanceBlue"] = 6
        keys["Saturation"] = 8
    if "portrait" in normalized:
        keys["Highlights"] = -10
        keys["Shadows"] = 12

    return apply_creative_direction(keys, prompt, constraints)
