from __future__ import annotations

import json
from typing import Any

import httpx

from app.core.ai.mock_generator import MockStyleGenerator
from app.core.models.ai import GeneratedStyleSpecResponse, PromptGenerateRequest
from app.core.models.style_spec import StyleSpec


class OllamaStyleGenerator:
    """Ollama-backed generator with safe fallback to mock generation."""

    def __init__(
        self,
        *,
        base_url: str = "http://localhost:11434",
        model: str = "llama3.1:8b",
        timeout_seconds: float = 20.0,
    ) -> None:
        self.provider = "ollama"
        self.model = model
        self.base_url = base_url.rstrip("/")
        self.timeout_seconds = timeout_seconds
        self._fallback = MockStyleGenerator(model=model)

    def generate_style_spec(self, payload: PromptGenerateRequest) -> GeneratedStyleSpecResponse:
        try:
            raw_json = self._generate_raw(payload)
            style_spec = self._parse_style_spec(raw_json, payload)
            return GeneratedStyleSpecResponse(
                style_spec=style_spec,
                rationale="Generated by local Ollama model from prompt instructions.",
                warnings=[],
                provider=self.provider,
                model=self.model,
            )
        except Exception as exc:  # pragma: no cover - exercised via explicit failure tests
            fallback = self._fallback.generate_style_spec(payload)
            fallback.provider = self.provider
            fallback.model = self.model
            fallback.warnings.append(f"Ollama generation failed; fallback mock used: {exc}")
            return fallback

    def _generate_raw(self, payload: PromptGenerateRequest) -> str:
        prompt = self._build_generation_prompt(payload)
        response = httpx.post(
            f"{self.base_url}/api/generate",
            json={
                "model": self.model,
                "prompt": prompt,
                "stream": False,
                "format": "json",
            },
            timeout=self.timeout_seconds,
        )
        response.raise_for_status()
        data = response.json()
        raw = data.get("response")
        if not isinstance(raw, str) or not raw.strip():
            raise ValueError("ollama response missing JSON payload")
        return raw

    def _parse_style_spec(self, raw_json: str, payload: PromptGenerateRequest) -> StyleSpec:
        parsed = json.loads(raw_json)
        if not isinstance(parsed, dict):
            raise ValueError("ollama response is not a JSON object")

        candidate: Any = parsed.get("style_spec", parsed)
        if not isinstance(candidate, dict):
            raise ValueError("ollama response missing style_spec object")

        if payload.intent and "intent" not in candidate:
            candidate["intent"] = payload.intent

        return StyleSpec.model_validate(candidate)

    def _build_generation_prompt(self, payload: PromptGenerateRequest) -> str:
        intent = payload.intent or []
        constraints = payload.constraints or {}
        payload_json = json.dumps(
            {
                "prompt": payload.prompt,
                "intent": intent,
                "constraints": constraints,
                "target": payload.target,
            },
            ensure_ascii=True,
        )
        return (
            "You generate Capture One style specs.\n"
            "Return only valid JSON, no markdown.\n"
            "JSON schema:\n"
            "{"
            '"name": "string", '
            '"intent": ["string"], '
            '"captureone": {"keys": {"Exposure": 0.2, "Contrast": 8}, "notes": "string optional"}'
            "}\n"
            "Constraints:\n"
            "- captureone.keys must contain at least one key.\n"
            "- values in captureone.keys must be string, int, or float.\n"
            "- prefer conservative edits suitable for reusable presets.\n"
            f"Input payload: {payload_json}"
        )
