from __future__ import annotations

import json
from typing import Any

import httpx

from app.core.ai.mock_generator import MockStyleGenerator
from app.core.models.ai import GeneratedStyleSpecResponse, PromptGenerateRequest
from app.core.models.style_spec import StyleSpec

_RICH_PRESET_DEFAULTS: dict[str, str | int | float] = {
    "Exposure": 0.1,
    "Contrast": 8,
    "Saturation": 6,
    "Clarity": 8,
    "Highlights": -8,
    "Shadows": 10,
    "WhiteBalanceTemperature": 5600,
    "WhiteBalanceTint": 2,
    "ColorBalanceRed": 3,
    "ColorBalanceGreen": 0,
    "ColorBalanceBlue": -2,
    "ToneCurve": "Film Standard",
}


class OllamaStyleGenerator:
    """Ollama-backed generator with safe fallback to mock generation."""

    def __init__(
        self,
        *,
        base_url: str = "http://localhost:11434",
        model: str = "llama3.1:8b",
        timeout_seconds: float = 20.0,
        cold_start_timeout_seconds: float = 90.0,
    ) -> None:
        self.provider = "ollama"
        self.model = model
        self.base_url = base_url.rstrip("/")
        self.timeout_seconds = timeout_seconds
        self.cold_start_timeout_seconds = cold_start_timeout_seconds
        self._fallback = MockStyleGenerator(model=model)

    def generate_style_spec(self, payload: PromptGenerateRequest) -> GeneratedStyleSpecResponse:
        try:
            raw_json = self._generate_raw(payload)
            style_spec = self._parse_style_spec(raw_json, payload)
            return GeneratedStyleSpecResponse(
                style_spec=style_spec,
                rationale="Generated by local Ollama model from prompt instructions.",
                warnings=[],
                provider=self.provider,
                model=self.model,
            )
        except Exception as exc:  # pragma: no cover - exercised via explicit failure tests
            fallback = self._fallback.generate_style_spec(payload)
            fallback.provider = self.provider
            fallback.model = self.model
            fallback.warnings.append(f"Ollama generation failed; fallback mock used: {exc}")
            return fallback

    def _generate_raw(self, payload: PromptGenerateRequest) -> str:
        prompt = self._build_generation_prompt(payload)
        request_body = {
            "model": self.model,
            "prompt": prompt,
            "stream": False,
            "format": "json",
            # Keep model resident for subsequent calls to reduce cold starts.
            "keep_alive": "10m",
        }
        try:
            response = httpx.post(
                f"{self.base_url}/api/generate",
                json=request_body,
                timeout=self.timeout_seconds,
            )
        except (httpx.ReadTimeout, httpx.ConnectTimeout):
            # Retry once with a longer timeout for first-load cold start.
            response = httpx.post(
                f"{self.base_url}/api/generate",
                json=request_body,
                timeout=self.cold_start_timeout_seconds,
            )
        response.raise_for_status()
        data = response.json()
        raw = data.get("response")
        if not isinstance(raw, str) or not raw.strip():
            raise ValueError("ollama response missing JSON payload")
        return raw

    def _parse_style_spec(self, raw_json: str, payload: PromptGenerateRequest) -> StyleSpec:
        parsed = json.loads(raw_json)
        if not isinstance(parsed, dict):
            raise ValueError("ollama response is not a JSON object")

        candidate: Any = parsed.get("style_spec", parsed)
        if not isinstance(candidate, dict):
            raise ValueError("ollama response missing style_spec object")

        if payload.intent and "intent" not in candidate:
            candidate["intent"] = payload.intent

        style_spec = StyleSpec.model_validate(candidate)
        if self._is_chat_delta_mode(payload):
            return style_spec
        return self._enrich_rich_preset(style_spec, payload)

    def _is_chat_delta_mode(self, payload: PromptGenerateRequest) -> bool:
        constraints = payload.constraints
        if not isinstance(constraints, dict):
            return False
        return constraints.get("mode") == "chat_turn_delta"

    def _enrich_rich_preset(self, style_spec: StyleSpec, payload: PromptGenerateRequest) -> StyleSpec:
        updated = style_spec.model_copy(deep=True)
        keys = dict(updated.captureone.keys)

        for key, default_value in _RICH_PRESET_DEFAULTS.items():
            keys.setdefault(key, default_value)

        prompt = payload.prompt.lower()
        if "warm" in prompt:
            keys["WhiteBalanceTemperature"] = max(2000, min(12000, int(float(keys["WhiteBalanceTemperature"])) + 350))
            keys["WhiteBalanceTint"] = max(-50, min(50, int(float(keys["WhiteBalanceTint"])) + 2))
            keys["ColorBalanceRed"] = max(-50, min(50, int(float(keys["ColorBalanceRed"])) + 1))
        if "cool" in prompt:
            keys["WhiteBalanceTemperature"] = max(2000, min(12000, int(float(keys["WhiteBalanceTemperature"])) - 350))
            keys["ColorBalanceBlue"] = max(-50, min(50, int(float(keys["ColorBalanceBlue"])) + 1))
        if "teal" in prompt:
            keys["ColorBalanceBlue"] = max(-50, min(50, int(float(keys["ColorBalanceBlue"])) + 3))
            keys["Saturation"] = max(-100, min(100, int(float(keys["Saturation"])) + 1))
        if "portrait" in prompt:
            keys["Highlights"] = max(-100, min(100, int(float(keys["Highlights"])) - 2))
            keys["Shadows"] = max(-100, min(100, int(float(keys["Shadows"])) + 2))

        updated.captureone.keys = keys
        return updated

    def _build_generation_prompt(self, payload: PromptGenerateRequest) -> str:
        intent = payload.intent or []
        constraints = payload.constraints or {}
        payload_json = json.dumps(
            {
                "prompt": payload.prompt,
                "intent": intent,
                "constraints": constraints,
                "target": payload.target,
            },
            ensure_ascii=True,
        )
        return (
            "You generate Capture One style specs.\n"
            "Return only valid JSON, no markdown.\n"
            "Do not include any explanation text outside JSON.\n"
            "JSON schema:\n"
            "{"
            '"name": "string", '
            '"intent": ["string"], '
            '"captureone": {"keys": {"Exposure": 0.2, "Contrast": 8, "Saturation": 6, "Clarity": 8, '
            '"Highlights": -8, "Shadows": 10, "WhiteBalanceTemperature": 5600, "WhiteBalanceTint": 2, '
            '"ColorBalanceRed": 3, "ColorBalanceGreen": 0, "ColorBalanceBlue": -2, "ToneCurve": "Film Standard"}, '
            '"notes": "string optional"}'
            "}\n"
            "Constraints:\n"
            "- captureone.keys must contain at least one key.\n"
            "- values in captureone.keys must be string, int, or float.\n"
            "- prefer conservative edits suitable for reusable presets.\n"
            "- for full preset generation, include ALL of these keys: Exposure, Contrast, Saturation, Clarity, "
            "Highlights, Shadows, WhiteBalanceTemperature, WhiteBalanceTint, ColorBalanceRed, ColorBalanceGreen, "
            "ColorBalanceBlue, ToneCurve.\n"
            "- keep values inside realistic ranges:\n"
            "  Exposure [-4,4], Contrast/Saturation/Clarity/Highlights/Shadows [-100,100], "
            "WhiteBalanceTemperature [2000,12000], WhiteBalanceTint [-50,50], "
            "ColorBalanceRed/Green/Blue [-50,50].\n"
            f"Input payload: {payload_json}"
        )
