from __future__ import annotations

import json
import os
from typing import Any

import httpx

from app.core.ai.mock_generator import MockStyleGenerator
from app.core.models.ai import (
    AIHealthResponse,
    AIPromptPreviewResponse,
    GeneratedStyleSpecResponse,
    PromptGenerateRequest,
)
from app.core.models.style_spec import StyleSpec

_RICH_PRESET_DEFAULTS: dict[str, str | int | float] = {
    "Exposure": 0.1,
    "Contrast": 8,
    "Saturation": 6,
    "Clarity": 8,
    "Highlights": -8,
    "Shadows": 10,
    "WhiteBalanceTemperature": 5600,
    "WhiteBalanceTint": 2,
    "ColorBalanceRed": 3,
    "ColorBalanceGreen": 0,
    "ColorBalanceBlue": -2,
    "ToneCurve": "Film Standard",
}
_TECHNICAL_PROMPT_EXAMPLES_PATH = os.path.join(
    os.path.dirname(__file__), "technical_prompt_examples.json"
)
_SEMANTIC_PROMPT_EXAMPLES_PATH = os.path.join(
    os.path.dirname(__file__), "semantic_prompt_examples.json"
)


class OllamaStyleGenerator:
    """Ollama-backed generator with safe fallback to mock generation."""

    def __init__(
        self,
        *,
        base_url: str = "http://localhost:11434",
        model: str = "llama3.1:8b",
        timeout_seconds: float = 20.0,
        cold_start_timeout_seconds: float = 90.0,
    ) -> None:
        self.provider = "ollama"
        self.model = model
        self.base_url = base_url.rstrip("/")
        self.timeout_seconds = timeout_seconds
        self.cold_start_timeout_seconds = cold_start_timeout_seconds
        self._fallback = MockStyleGenerator(model=model)

    def generate_style_spec(self, payload: PromptGenerateRequest) -> GeneratedStyleSpecResponse:
        try:
            raw_json = self._generate_raw(payload)
            style_spec = self._parse_style_spec(raw_json, payload)
            return GeneratedStyleSpecResponse(
                style_spec=style_spec,
                rationale="Generated by local Ollama model from prompt instructions.",
                warnings=[],
                provider=self.provider,
                model=self.model,
            )
        except Exception as exc:  # pragma: no cover - exercised via explicit failure tests
            fallback = self._fallback.generate_style_spec(payload)
            fallback.provider = self.provider
            fallback.model = self.model
            fallback.warnings.append(f"Ollama generation failed; fallback mock used: {exc}")
            return fallback

    def preview_prompt(self, payload: PromptGenerateRequest) -> AIPromptPreviewResponse:
        rendered_prompt, selected_examples = self._build_generation_prompt(payload)
        return AIPromptPreviewResponse(
            provider=self.provider,
            model=self.model,
            prompt=rendered_prompt,
            examples_count=len(selected_examples),
            examples=selected_examples,
        )

    def health_check(self) -> AIHealthResponse:
        try:
            response = httpx.get(
                f"{self.base_url}/api/tags",
                timeout=min(self.timeout_seconds, 10.0),
            )
            response.raise_for_status()
            payload = response.json()
        except Exception as exc:  # noqa: BLE001
            return AIHealthResponse(
                status="unavailable",
                available=False,
                provider=self.provider,
                model=self.model,
                message=f"Ollama is unreachable at {self.base_url}: {exc}",
            )

        models = payload.get("models", [])
        available_models = {
            str(model.get("name", "")).strip()
            for model in models
            if isinstance(model, dict) and str(model.get("name", "")).strip()
        }
        if self.model in available_models:
            return AIHealthResponse(
                status="available",
                available=True,
                provider=self.provider,
                model=self.model,
                message=f"Ollama is reachable and model {self.model} is installed.",
            )

        return AIHealthResponse(
            status="degraded",
            available=False,
            provider=self.provider,
            model=self.model,
            message=(
                f"Ollama is reachable at {self.base_url}, but model {self.model} is not installed."
            ),
        )

    def _generate_raw(self, payload: PromptGenerateRequest) -> str:
        prompt, _ = self._build_generation_prompt(payload)
        request_body = {
            "model": self.model,
            "prompt": prompt,
            "stream": False,
            "format": "json",
            # Keep model resident for subsequent calls to reduce cold starts.
            "keep_alive": "10m",
        }
        try:
            response = httpx.post(
                f"{self.base_url}/api/generate",
                json=request_body,
                timeout=self.timeout_seconds,
            )
        except (httpx.ReadTimeout, httpx.ConnectTimeout):
            # Retry once with a longer timeout for first-load cold start.
            response = httpx.post(
                f"{self.base_url}/api/generate",
                json=request_body,
                timeout=self.cold_start_timeout_seconds,
            )
        response.raise_for_status()
        data = response.json()
        raw = data.get("response")
        if not isinstance(raw, str) or not raw.strip():
            raise ValueError("ollama response missing JSON payload")
        return raw

    def _parse_style_spec(self, raw_json: str, payload: PromptGenerateRequest) -> StyleSpec:
        parsed = json.loads(raw_json)
        if not isinstance(parsed, dict):
            raise ValueError("ollama response is not a JSON object")

        candidate: Any = parsed.get("style_spec", parsed)
        if not isinstance(candidate, dict):
            raise ValueError("ollama response missing style_spec object")

        if payload.intent and "intent" not in candidate:
            candidate["intent"] = payload.intent

        style_spec = StyleSpec.model_validate(candidate)
        if self._is_chat_delta_mode(payload):
            return style_spec
        return self._enrich_rich_preset(style_spec, payload)

    def _is_chat_delta_mode(self, payload: PromptGenerateRequest) -> bool:
        constraints = payload.constraints
        if not isinstance(constraints, dict):
            return False
        return constraints.get("mode") == "chat_turn_delta"

    def _enrich_rich_preset(self, style_spec: StyleSpec, payload: PromptGenerateRequest) -> StyleSpec:
        updated = style_spec.model_copy(deep=True)
        keys = dict(updated.captureone.keys)

        for key, default_value in _RICH_PRESET_DEFAULTS.items():
            keys.setdefault(key, default_value)

        prompt = payload.prompt.lower()
        if "warm" in prompt:
            keys["WhiteBalanceTemperature"] = max(2000, min(12000, int(float(keys["WhiteBalanceTemperature"])) + 350))
            keys["WhiteBalanceTint"] = max(-50, min(50, int(float(keys["WhiteBalanceTint"])) + 2))
            keys["ColorBalanceRed"] = max(-50, min(50, int(float(keys["ColorBalanceRed"])) + 1))
        if "cool" in prompt:
            keys["WhiteBalanceTemperature"] = max(2000, min(12000, int(float(keys["WhiteBalanceTemperature"])) - 350))
            keys["ColorBalanceBlue"] = max(-50, min(50, int(float(keys["ColorBalanceBlue"])) + 1))
        if "teal" in prompt:
            keys["ColorBalanceBlue"] = max(-50, min(50, int(float(keys["ColorBalanceBlue"])) + 3))
            keys["Saturation"] = max(-100, min(100, int(float(keys["Saturation"])) + 1))
        if "portrait" in prompt:
            keys["Highlights"] = max(-100, min(100, int(float(keys["Highlights"])) - 2))
            keys["Shadows"] = max(-100, min(100, int(float(keys["Shadows"])) + 2))

        updated.captureone.keys = keys
        return updated

    def _build_generation_prompt(self, payload: PromptGenerateRequest) -> tuple[str, list[dict[str, Any]]]:
        intent = payload.intent or []
        constraints = payload.constraints or {}
        payload_json = json.dumps(
            {
                "prompt": payload.prompt,
                "intent": intent,
                "constraints": constraints,
                "target": payload.target,
            },
            ensure_ascii=True,
        )
        selected_examples = self._select_prompt_examples(payload)
        examples_json = json.dumps(selected_examples, ensure_ascii=True)
        prompt = (
            "You generate Capture One style specs.\n"
            "Return only valid JSON, no markdown.\n"
            "Do not include any explanation text outside JSON.\n"
            "JSON schema:\n"
            "{"
            '"name": "string", '
            '"intent": ["string"], '
            '"captureone": {"keys": {"Exposure": 0.2, "Contrast": 8, "Saturation": 6, "Clarity": 8, '
            '"Highlights": -8, "Shadows": 10, "WhiteBalanceTemperature": 5600, "WhiteBalanceTint": 2, '
            '"ColorBalanceRed": 3, "ColorBalanceGreen": 0, "ColorBalanceBlue": -2, "ToneCurve": "Film Standard"}, '
            '"notes": "string optional"}'
            "}\n"
            "Constraints:\n"
            "- captureone.keys must contain at least one key.\n"
            "- values in captureone.keys must be string, int, or float.\n"
            "- prefer conservative edits suitable for reusable presets.\n"
            "- for full preset generation, include ALL of these keys: Exposure, Contrast, Saturation, Clarity, "
            "Highlights, Shadows, WhiteBalanceTemperature, WhiteBalanceTint, ColorBalanceRed, ColorBalanceGreen, "
            "ColorBalanceBlue, ToneCurve.\n"
            "- keep values inside realistic ranges:\n"
            "  Exposure [-4,4], Contrast/Saturation/Clarity/Highlights/Shadows [-100,100], "
            "WhiteBalanceTemperature [2000,12000], WhiteBalanceTint [-50,50], "
            "ColorBalanceRed/Green/Blue [-50,50].\n"
            "Reference examples (real styles, use as aesthetic guidance):\n"
            f"{examples_json}\n"
            f"Input payload: {payload_json}"
        )
        return prompt, selected_examples

    def _select_prompt_examples(self, payload: PromptGenerateRequest) -> list[dict[str, Any]]:
        technical_examples = _load_prompt_examples(_TECHNICAL_PROMPT_EXAMPLES_PATH)
        semantic_examples = _load_prompt_examples(_SEMANTIC_PROMPT_EXAMPLES_PATH)
        if not technical_examples and not semantic_examples:
            return []

        max_examples_raw = os.getenv("STYLEAGENT_AI_MAX_PROMPT_EXAMPLES", "4").strip()
        try:
            max_examples = max(1, min(8, int(max_examples_raw)))
        except ValueError:
            max_examples = 4

        prompt_tokens = set(payload.prompt.lower().replace("-", " ").split())
        intent_tokens = {token.lower() for token in (payload.intent or [])}

        technical_budget = max_examples
        semantic_budget = 0
        if semantic_examples and max_examples > 1:
            semantic_budget = 1
            technical_budget = max_examples - 1

        selected: list[dict[str, Any]] = []
        selected.extend(
            self._score_and_select_examples(
                examples=technical_examples,
                prompt_tokens=prompt_tokens,
                intent_tokens=intent_tokens,
                limit=technical_budget,
            )
        )
        if semantic_budget:
            selected.extend(
                self._score_and_select_examples(
                    examples=semantic_examples,
                    prompt_tokens=prompt_tokens,
                    intent_tokens=intent_tokens,
                    limit=semantic_budget,
                )
            )

        if len(selected) < max_examples:
            remaining_examples = [
                example
                for example in technical_examples + semantic_examples
                if example not in selected
            ]
            selected.extend(
                self._score_and_select_examples(
                    examples=remaining_examples,
                    prompt_tokens=prompt_tokens,
                    intent_tokens=intent_tokens,
                    limit=max_examples - len(selected),
                )
            )

        return [
            {
                "source": example.get("source"),
                "prompt": example.get("prompt"),
                "style_spec": example.get("style_spec"),
            }
            for example in selected[:max_examples]
        ]

    def _score_and_select_examples(
        self,
        *,
        examples: list[dict[str, Any]],
        prompt_tokens: set[str],
        intent_tokens: set[str],
        limit: int,
    ) -> list[dict[str, Any]]:
        if limit <= 0 or not examples:
            return []

        scored: list[tuple[int, dict[str, Any]]] = []
        for example in examples:
            tags = {str(tag).lower() for tag in example.get("tags", [])}
            prompt_text = str(example.get("prompt", "")).lower()
            prompt_matches = sum(1 for token in prompt_tokens if token in prompt_text or token in tags)
            intent_matches = sum(2 for token in intent_tokens if token in tags)
            score = prompt_matches + intent_matches
            scored.append((score, example))

        scored.sort(key=lambda item: item[0], reverse=True)
        return [example for _, example in scored[:limit]]


def _load_prompt_examples(path: str) -> list[dict[str, Any]]:
    try:
        with open(path, encoding="utf-8") as handle:
            loaded = json.load(handle)
    except Exception:  # noqa: BLE001
        return []
    if not isinstance(loaded, list):
        return []
    return [item for item in loaded if isinstance(item, dict)]
